<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Correlate.AspNetCore" Version="6.0.0" />
    <PackageVersion Include="Marten" Version="8.11.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="9.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.9" />
    <PackageVersion Include="Seq.Extensions.Logging" Version="8.0.0" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.1.118" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="9.0.4" />
    <PackageVersion Include="WolverineFx" Version="4.12.2" />
    <PackageVersion Include="WolverineFx.FluentValidation" Version="4.12.2" />
    <PackageVersion Include="WolverineFx.Http" Version="4.12.2" />
    <PackageVersion Include="WolverineFx.RabbitMQ" Version="4.12.2" />
  </ItemGroup>
</Project>